export const ACTIONS = {
  // DateCounter
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_COUNT: "SET_COUNT",
  SET_STEP: "SET_STEP",
  RESET: "RESET",
  // QUIZ
  DATA_RECIEVED: "DATA_RECIEVED",
  DATA_FAILED: "DATA_FAILED",
  QUIZ_START: "QUIZ_START",
  SET_ANSWER: "SET_ANSWER",
  NEXT_QUESTION: "NEXT_QUESTION",
  FINISH_QUIZ: "FINISH_QUIZ",
  RESET_QUIZ: "RESET_QUIZ",
  TICK: "TICK",
};
