export const ACTIONS = {
  OPEN_ACCOUNT: "OPEN_ACCOUNT",
  CLOSE_ACCOUNT: "CLOSE_ACCOUNT",
  SET_WITHDRAW_AMOUNT: "SET_WITHDRAW_AMOUNT",
  WITHDRAW: "WITHDRAW",
  SET_DEPOSIT_AMOUNT: "SET_DEPOSIT_AMOUNT",
  DEPOSIT: "DEPOSIT",
  SET_LOAN_AMOUNT: "SET_LOAN_AMOUNT",
  TAKE_LOAN: "TAKE_LOAN",
  PAY_LOAN: "PAY_LOAN",
};
